### ISSUE TITLE
Seeds are crashing whole game

### ISSUE THREAD

**Issue by Brodatv** [DeathByKorea/BrokeProtocol#102]
So, I decided to make a new thumbnails for my vids on Youtube and I took cannabis seed to make some drugpacks.

Aaaand... placing it is impossible, game says "Not suitable area"

Also you cant do anything, you can't switch to other item, open doors, enter cars, go to your home. Game isn't running local server again if you are playing offline, infinite loading. Music in background, animation on screen but you can't log in or register. You have to unpack game again to make it working.

**Comment by BrokeProtocol** [comment]
I think you have to close existing processes in task manager to fix the  infinite loading thing in offline mode:
![loadingscreen](https://user-images.githubusercontent.com/29849122/28248982-e897e274-6a1b-11e7-8fe8-1a8061be88fe.png)
![processes](https://user-images.githubusercontent.com/29849122/28248983-e8981730-6a1b-11e7-9280-1e559eea40e6.png)

**Comment by DeathByKorea** [comment]
Closed, Fixed in 0.66test2
