### ISSUE TITLE
Placed items in apartments appear to become above the apartment after relogging

### ISSUE THREAD

**Issue by DeathByKorea** [DeathByKorea/BrokeProtocol#125]
![1](https://cdn.discordapp.com/attachments/312436123278376961/336550111364775939/unknown.png)

![2](https://cdn.discordapp.com/attachments/312436123278376961/336550111364775939/unknown.png)

![3](https://cdn.discordapp.com/attachments/312436123278376961/336549225682829324/image.png)

![4](https://cdn.discordapp.com/attachments/312436123278376961/336550606808547338/unknown.png)

**Comment by BrokeProtocol** [comment]
Fixed in test version 10.
