### ISSUE TITLE
Apartment Frozen Bug.. aka stuck in time loop.

### ISSUE THREAD

**Issue by DarkRosanne** [DeathByKorea/BrokeProtocol#132]
To start off, This happened after a relog with my apartment being wiped clean and its content floating above it.

https://pasteboard.co/GBuqzDp.png

After this I asked if we could test to see if anything happened upon selling the apartment while he was inside.
This resulted in everything stopping in time for both of us, some characters which were moving were looping back like a tracer does when she jumps back every now and then *best current reference to give*.
For him, he got kicked out and same thing, as if we basically entered our own time fracture.
Its probably easily done to re-create this bug so you can see what actually happens.

**Comment by DeathByKorea** [comment]
Similar to #126 ? Fixed in .66test10?

**Comment by DarkRosanne** [comment]
Nope not like that. more like i can walk around but everything else is either frozen or looping back in time. its like your stuck in a 2 second time loop except your not effected by it, i could hit people and everything but it would cause nothing. When i talked no-one could hear me, a bit like a de-sync but also not if you get what i mean?

**Comment by BrokeProtocol** [comment]
Does this still happen with latest hotfix?
