### ISSUE TITLE
Font with the new update (v0.66)

### ISSUE THREAD

**Issue by PunInABun** [DeathByKorea/BrokeProtocol#133]
With the new update i saw that the font is the same but now its blurry, like it was a low quality or something, can you please put it in the way it was before??

How it was before :

![screenshot_3](https://user-images.githubusercontent.com/30134946/28322485-21db10de-6bce-11e7-89a6-1246aed5c507.jpg)

How it is now : 

![screenshot_1](https://user-images.githubusercontent.com/30134946/28322530-4356652e-6bce-11e7-847d-597d9afbaf4b.jpg)

If you fullscreen it, you can see the big difference!

**Comment by BrokeProtocol** [comment]
Is this fixed?
