### ISSUE TITLE
Apt Server Crash

### ISSUE THREAD

**Issue by Aurctic** [DeathByKorea/BrokeProtocol#139]
You you invite a player in your apartment and you disconnect it'll make the server hang and no one is able to login.

**Comment by DarkRosanne** [comment]
That;s basically the bug I had too :/ I think it probably just doesn't know where to place you after its done.

**Comment by BrokeProtocol** [comment]
https://youtu.be/y6yMnCROl3A  — courtesy of tellst1

**Comment by BrokeProtocol** [comment]
If you are a server owner, I uploaded a modified Assembly-CSharp.dll that disables inviting, check the Discord's pinned messages in "#general".

**Comment by Aurctic** [comment]
Fixed with the new update.
