### ISSUE TITLE
Damage taken/loss of HP when entering your apartment.

### ISSUE THREAD

**Issue by BPGang** [DeathByKorea/BrokeProtocol#140]
Definitely not the first time I've seen it mentioned here and there on BP servers.

Happened to me today, kept losing HP when entering my apartment but as soon as I would leave the damage taking/loss of HP would stop immediately, and restart when I enter my apartment.

Video of the incident: https://vid.me/LyN3i

Random title + spooky comment for the fun of it, but seriously please. Fix the bug D:

**Comment by Aurctic** [comment]
Having the same issue, noticed it was only with certain people.

**Comment by BrokeProtocol** [comment]
Fixed I think?
