### ISSUE TITLE
Items disappearing from chests.

### ISSUE THREAD

**Issue by BPGang** [DeathByKorea/BrokeProtocol#141]
When you place a chest in your apartment and store items in it and leave it there for a while, if you come back to it X mins/hours/whatever later most if not all of the items in there disappear and a random item that you had placed in the chest would be laying on the floor near the chest as a loose item.

Please fix this, it's really annoying coming back home to find a random loose medkit/gun/whatever and an almost empty chest....

**Comment by DeathByKorea** [comment]
Closed, Fixed with #147

**Comment by DeathByKorea** [comment]
Sike! Not fixed, will be for steam hopefully

**Comment by DeathByKorea** [comment]
Finally fixed in steam release 0.67
