### ISSUE TITLE
Apartments / Items coming out of chests and being placed under the floor.

### ISSUE THREAD

**Issue by Caza397** [DeathByKorea/BrokeProtocol#147]
Not sure how to reproduce this reliably but sometimes when I enter my apartment, there are items missing from my chest and I find that they have been placed under the floor (Screenshot), These items contribute towards the furniture limit and results in some of my furniture being removed.
![fdfsd](https://user-images.githubusercontent.com/30003238/28472836-80f4fc38-6e85-11e7-9709-b3f13763ee05.PNG)

**Comment by DeathByKorea** [comment]
Fixed in next patch!
