### ISSUE TITLE
server.bat still tells to open ports 5555 5556

### ISSUE THREAD

**Issue by iwanPlays** [DeathByKorea/BrokeProtocol#150]
server.bat still tells to open ports 5555 5556 as of 0.666

we need some kind of output to know whether the server was able to run and connect properly.

**Comment by BrokeProtocol** [comment]
This is not a bug! That message simply shows up because the echo in the .bat file hasn't been changed, you can do this your self.

**Comment by iwanPlays** [comment]
You're right. Just letting you know because the text is documentation, the documentation has an issue. might lead to failing hosts requiring support because they rely on that message only.

**Comment by Ternzeeh** [comment]
he's got a point though

**Comment by DeathByKorea** [comment]
Reopening, but without bug tag. As it could be a legitimate problem.

**Comment by UserR00T** [comment]
Issue seemed to be resloved in latest update.
