### ISSUE TITLE
Can't join to a server

### ISSUE THREAD

**Issue by iTzTati** [DeathByKorea/BrokeProtocol#151]
It says "Please Wait..." when i try to join that server, but if i go to other server it does let me. Already restarted the game and the pc, Also talked with the server owner

**Comment by iwanPlays** [comment]
Perhaps their server version is different from your game version?

**Comment by Ternzeeh** [comment]
It is possible that you have been banned from that server, btw we might have to close this soon since you are asking for help instead of posting anything relevant to the forum's purpose, you can ask in the help channel on Discord instead. :D

**Comment by iwanPlays** [comment]
suggestion: if user is banned from a server, inform them of that fact.

that increases probability of anger but reduces the probability of false issue reports/support requests (hopefully).

Not sure which is better.

**Comment by BrokeProtocol** [comment]
Closed.
