### ISSUE TITLE
Voice Chat icon and volume bar

### ISSUE THREAD

**Issue by iwanPlays** [DeathByKorea/BrokeProtocol#152]
As a player, I have no way to be sure my voice button is working and my voice is being sent.

When the voice chat feature is activated by me, show a speaker icon.

Next to or above the speaker icon, please show a bar, that indicates the volume of my voice, so I know the operating system audio settings allow the audio to work properly.

**Comment by BrokeProtocol** [comment]
Duplicate: https://github.com/DeathByKorea/BrokeProtocol/issues/97
