### ISSUE TITLE
Weird box in the top left corner of the Server List

### ISSUE THREAD

**Issue by UserR00T** [DeathByKorea/BrokeProtocol#159]
When you click the box your game will freaze. Thats it.
You have to restart the game to unfreeze it

Proof: https://puu.sh/wRGZA/ee9351798d.mp4

**Comment by BrokeProtocol** [comment]
Thanks for reporting this bug.

**Comment by BrokeProtocol** [comment]
Still present in 0.70

![](https://i.imgur.com/p7Gqn6z.png)

**Comment by NongBenz** [comment]
This is for debugging for me... it turns the game into a server for testing purposes. Maybe will hide for production in the future.

**Comment by UserR00T** [comment]
Alright
