### ISSUE TITLE
Battle Royale Bug

### ISSUE THREAD

**Issue by Ternzeeh** [DeathByKorea/BrokeProtocol#181]
When a player is downed, he is still able to join a Battle Royale and when he does, his incapacitated body will teleport to a spawn and stay there but you will be able to walk and interact normally although you won't have a body nor see what you are holding. I am not sure if people can see you while in this state; bug can be fixed by suiciding. You are still "invisible" even after the battle royale has ended and you've won.

P.S Could be a major bug if people can't actually see you meaning you're invisible.

**Comment by BrokeProtocol** [comment]
Can still join Battle Royal while knocked out but you die few seconds after joining. Tested in 0.72
