### ISSUE TITLE
Free Humvee

### ISSUE THREAD

**Issue by Ternzeeh** [DeathByKorea/BrokeProtocol#182]
Using a lock pick on a Humvee (not owned by you) will allow you to own the Humvee without buying it but if it gets destroyed and re spawns back, the car is still yours. That is not how lock picks should work IMO since you only pick the car's lock (while consuming the lock pick in the process) and not having an actual "key" to it for you to be able to enter it. Having to drive it again after it gets destroyed should require you to lock pick it again.

**Comment by BrokeProtocol** [comment]
Could not reproduce in 0.72, it just unlocked the vehicle. Owner has to lock the vehicle again to protect.
