### ISSUE TITLE
Incorrect/Not detected Hitboxes

### ISSUE THREAD

**Issue by Ternzeeh** [DeathByKorea/BrokeProtocol#186]
Sometimes when I hit a player with a bullet, it doesn't count and the player doesn't get damaged. It could be server lag or something in the coding is taking too long.
-REDLAVA/teco

This also include cars and melee fighting. When trying to run over people, there is a chance that the player isn't actually hit and has no damage dealt even when it looked like you actually rammed him over. Oh and since reckless driving will cause damage to the driver, there is a chance that driving into another car or object with the far edge of your car's front won't deal damage to you.

**Comment by Aurctic** [comment]
I've noticed this, even times where I've shot a player down but they weren't hurt by it but still knocked down.

**Comment by BrokeProtocol** [comment]
I think this is just a problem with latency, something that is an issue with every multiplayer game. Going to close since it's not really something that could be easily fixed.
