### ISSUE TITLE
Glitching out of the buildings.

### ISSUE THREAD

**Issue by ekcja** [DeathByKorea/BrokeProtocol#193]
You can glitch out of any building if you have an object that is close to the roof and you can go on it. If you go on it while crouching and then you will take off your finger out of ctrl button, you can glitch outside on the roof. I tried it in the restaurant, I went on the bin crouching, I stopped crouching and I got outside on the roof to be exact, I could walk like a normal person, I don't know if I could fall from it to the void, I didn't check it. Fix it please.

**Comment by Ternzeeh** [comment]
did you actually go outside the "box" of the restaurant? Based on my experience, you can only put your head in to the roof and see the void in first person and yes, you can walk , walk in air. :3

**Comment by BrokeProtocol** [comment]
Was able to look outside the interior but could not actually glitch outside of it and move around.

![](https://i.imgur.com/iXQOt1n.png)
