### ISSUE TITLE
Problems with a city

### ISSUE THREAD

**Issue by KaroYT** [DeathByKorea/BrokeProtocol#201]
![image](https://user-images.githubusercontent.com/30978815/29250090-66f62c6c-803c-11e7-938c-6f1d7eb8aa4c.png)
I dont have a city. I downloaded game from gamejolt 2 times and nothing works. I need help

**Comment by DeathByKorea** [comment]
Closed, Try asking in Discord, https://discord.gg/D2fzmXp

**Comment by Miguimops021** [comment]
Me too (But in this intercafe)

**Comment by KaroYT** [comment]
I came from discord and the cant help me
