### ISSUE TITLE
New Ideas For The Game BrokeProtocol!

### ISSUE THREAD

**Issue by Miguimops021** [DeathByKorea/BrokeProtocol#202]
On first im form spain and im not too good for write!

The first thing are the smartphones, you can make a private email for users, using the smartphone, and you can call to a emergency place, and 1 of the online user (what´s have the job) have a mark place on the minimap. (Like for pizza livery and a burger livery)

For second one, you can put for admin options, give (item) (quantity) and a godmode (I hate when kill me when im solve a problem with users!

For Third, you can make all buildings (homes) habitable an all markets accesible, (like pizzerias, boutiques [Like clothes and shoes] {and all whit respective vehicles}){Like motorbikes for pizza delivery and buses}

For Fourth, you can make new cars (like deportives and muscle cars etc) 

For Fifth, make FEMALE MODELS (for NPC and Players) 

For Sixth, You can make the map a little big, (when you put helicopters, this little map in 6 seconds can you make a cross the map) and put more ATM in the streets 

For Sevent, Swiming in the beach have a boat and (fishing (?))

For Eight, please more Clothes and More Bulletproof (Not only the Riot) {Military Clothes are realy COOL!!!!!!!} 

I Can help you in this August and September if you want 

-Contact-

Email: miguelloko021@gmail.com // jaggerbunn@gmail.com
Skype: sempaitemo
Discord: Mario(Medico)#2441

**Comment by BrokeProtocol** [comment]
Please split up the suggestions into individual "Issues" so it's easier to read at a glance.
