### ISSUE TITLE
Flashlight 'light' doesnt spawn/render correctly

### ISSUE THREAD

**Issue by UserR00T** [DeathByKorea/BrokeProtocol#210]
The light source isnt at the front, but at the middle/back

Screens: [1](http://i.imgur.com/iZNimHp.png) | [2](http://i.imgur.com/DaD48qa.png) | [3](http://i.imgur.com/8kYFPSi.png)

**Comment by Ternzeeh** [comment]
good eyesight as always

**Comment by UserR00T** [comment]
;)

**Comment by BrokeProtocol** [comment]
v0.72 https://i.imgur.com/kkH2DZF.png

**Comment by UserR00T** [comment]
Will get fixed in newest version, 0.73.
