### ISSUE TITLE
Suggestions about the prison.

### ISSUE THREAD

**Issue by HamsterOh** [DeathByKorea/BrokeProtocol#211]
Hello. Why not make two prison. One like alcatraz, a big prison on a island wich we can reach only with helicopter ? :+1: The big prison will be only for people who have a lot of fine !

**Comment by Knowie** [comment]
amazing idea :D

**Comment by korterkaks** [comment]
good one!

**Comment by Vixonary** [comment]
Unfortunately, they can just choose to suicide, which really defeats the purpose of the big prison then.
