### ISSUE TITLE
Make the clouds higher

### ISSUE THREAD

**Issue by UserR00T** [DeathByKorea/BrokeProtocol#216]
The cloud should be higher, because its very annoying.
http://i.imgur.com/E5MPwCo.png
http://i.imgur.com/ebuHB5h.png

**Comment by Ternzeeh** [comment]
my chat omg

**Comment by UserR00T** [comment]
Ahahah XD

**Comment by UserR00T** [comment]
Has been added in ``v0.72 - The Chase Camera Update:``

``Raised cloud height``
