### ISSUE TITLE
More Gang Activities

### ISSUE THREAD

**Issue by Manadore** [DeathByKorea/BrokeProtocol#218]
There should be a way to you recruit members (bots) from your gang so they can follow you, help you doing heists etc and also of we starting gang wars, they should start by themselves and when we start a gang war, nearby gang members of our gang should come help us. Secondly, when were in a gang we should be able to see them on the map.

**Comment by BrokeProtocol** [comment]
Duplicate: https://github.com/DeathByKorea/BrokeProtocol/issues/5
