### ISSUE TITLE
Vehicle locks

### ISSUE THREAD

**Issue by D3rp6** [DeathByKorea/BrokeProtocol#220]
Once you leave the current session your personal car/plane no longer has a lock,and everyone can enter it,including you.

**Comment by UserR00T** [comment]
Doesnt it do that already?

**Comment by D3rp6** [comment]
I mean personal vehicles

**Comment by UserR00T** [comment]
Oh sorry. I didnt get the question, you mean if you bought the car/plane and you rejoin it wont be locked again?

**Comment by Ternzeeh** [comment]
I think this is supposed to be a bug.

**Comment by BrokeProtocol** [comment]
Closing this issue because of duplicate and is better explained here: https://github.com/DeathByKorea/BrokeProtocol/issues/223
