### ISSUE TITLE
Suggestions And Problems

### ISSUE THREAD

**Issue by PliveOwO** [DeathByKorea/BrokeProtocol#222]
_**Suggestions**_
~Cockpit in the Helicopter or just the think to know if your helicopter is going in a 30 Degree so it wont be Confusing
~Suggestion Channel in Discord
~Accesable Chest in your Appartment to put all of the things that you dont need at the Moment
~The Club You know what i mean the G*rls Club you know what i mean right ???
~Jets = Fun
~grass or something that can plant a Drug seeds inside your appartment

_**Problems**_
~When in Helicopter all of you stuff will be gone and cant get it back
~ When you already buy [IDK The of buy plural, sorry] the helicopter then when you Relogin you dont have the Helicopter Purchased

 ~Plive~

**Comment by Ternzeeh** [comment]
"~When in Helicopter all of you stuff will be gone and cant get it back"
 Can you explain it further?

**Comment by PliveOwO** [comment]
when you enter in the helicopter the 1st time its ok but in the 2nd time all of your item will be gone but the clothes is still there
