### ISSUE TITLE
Suggestions - Submitted Via Steam Forums

### ISSUE THREAD

**Issue by Kagemd** [DeathByKorea/BrokeProtocol#224]
**# Broke Protocol Suggestions 
_Steam Forums_**  

**VOLUME INCREASE** 
_Increase the distance at which Gunshots and Explosions can be heard._  
Louder gunshots that travel further. Simple changes, big differences. Gunfire could attract nearby, or even far away police officers. Gunshots as of right now are extremely quiet and barely travel more than a few feet. The city is pretty small, so a gunshot could be heard by almost everyone unless suppressed (which would only reduce the distance by a small amount), or if they fired from within a building. Car explosions, or any other explosion, could also stand to be louder. 

**NPC Movements** 
_Allow NPC's to deviate from their current objectives_  
Some variance in NPC paths. This is a little more complex. NPCs should be able to deviate from their path a little when not distracted to make them seem more 'alive'. As long as they make sure to stay off the roads, of course. 

**AI Interactions/Personality** 
_Allow for more interaction and ranging personalities from an AI (NPC_)  
More AI interactivity, mainly picking things up. Dropped items should be looted by other NPCs if their owners are gone and it isn't considered 'illegal' by the NPC (unless another factor, which I'll suggest later, changes this). Even if this didn't apply to civilian NPCs, some sort of system should be put into place for police NPCs. They could pick up and destroy contraband, or if one of their fellow officers is killed, they will go to their corpse and pick up their weaponry so it won't fall into the hands of a criminal. 

_AI personalities._ 
This is a difficult one. NPCs should have different 'personality' stats that dictate their actions. It could be split into a few randomized numbers that change how they react to certain actions. I can't think off a list of personality variables off the top of my head, but an example of one could be courage. A NPC with an especially high courage stat would better resist attempts to be mugged. They'd either tell you to go away and possibly call the cops, or if especially courageous, will fight back. An NPC with a low courage stat would run away from a mugging (or just give you their stuff), or when attacked or when shots are fired. ETC. Certain NPCs would be more likely to commit illegal actions than others. 

**Mouse Movements** 
_Allow for the mouse to be inverted_  
Could you please include the option to invert Y-Axis with Mouse Look? 

**Wanted Level(s)** 
_Longer suicide timer for those who suicide with more than X amount of stars_  
When you are wanted (you robbed the bank, gun store, whatever) and you bought an apartment, stored your loot and you have still 5 stars. Well, you are too lazy to wait so you suicide. And spawn back in 10 seconds. This should be changed. When you suicide while you are wanted, you should be dead for longer. When I arrest someone with 10k bounty, they suicide just before I'm at the jail. And I lose that money. People who suicide just to get rid of wanted levels, should get penalty. 

**Achievements/Trading Cards** 
_Steam Achievements and Trading Cards_  
For gamers who like to achieve goals and collect Trading Cards in Steam.

**Comment by UserR00T** [comment]
Good idea. 👍

**Comment by BrokeProtocol** [comment]
Please split suggestions into their own "Issue" for easy viewing what the suggestion/bug is about.
