### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by TheDman131** [DeathByKorea/BrokeProtocol#227]
1. Tow truck
if a car is just sitting there blocking traffic or is owned by a criminal you can tow it and earn cash

2. Highways(iffy) 
I know you guys are working on different areas of the map like a beach a country side etc. I don't know if you are planning on putting it together as one island I would highly suggest you add the country side and other extensions as separate islands and connect them with highways, bigger roads make for great police chases.

3 computer gun (single player maybe multi) 
law enforcement is really hard to use in a game especially the tools, instead of having a computer in a police car why not a gun that is linked to a law database. you would aim it like a real gun and fire it too but instead of a bullet or anything coming out it scans the car and on a black screen on the gun or user chat(only you can see it) will tell you if its stolen or the guy that owns it is wanted you could call a tow truck and have it towed 

4 more fire stuff to do
what I mean is realistically speaking there are calls that happen a lot more often the fires do like vehicle accidents why not make that a call where you call pull out AI civ's from their cars and drag them to safety and if injured call an ambulance to take them away and is there any way to have building fires where you can drive a fire truck to a building equip an air tank and go into the building and fight the fire and possibly rescue civilians.

**Comment by BrokeProtocol** [comment]
Please split suggestions into their own "Issue".
