### ISSUE TITLE
Third person camera doesnt reset when put in jail

### ISSUE THREAD

**Issue by UserR00T** [DeathByKorea/BrokeProtocol#228]
Video explains it all. https://puu.sh/xpP7L/6b63ec397d.mp4

**Comment by DeathByKorea** [comment]
Don't think this is a bug, It's more of a freecam that's centered on the player, and the camera focus shifts towards the player in jail.

**Comment by merchantjoker** [comment]
Try pressing alt+F4

**Comment by BrokeProtocol** [comment]
Not really a bug, the third person mode is more of a tool to take screenshots.
