### ISSUE TITLE
NO IN GAME SOUNDS 

### ISSUE THREAD

**Issue by merchantjoker** [DeathByKorea/BrokeProtocol#230]
I have tried all possible solutions for getting this problem to be fixed it seems like no one els is having this problem but me. its only broke protocol and roblox I'm having the sound problem with if any one has had this problem please let me know how to fix it I would like to be able to play the game with in game sounds.

**Comment by UserR00T** [comment]
If it is some other software too, it could be the fault of windows; try replugging your headset before starting the game again.

**Comment by merchantjoker** [comment]
Reported for troling dude

**Comment by Kagemd** [comment]
Really, for trolling? R00T is by far a troll but you wouldn't know that.

He was giving you an honest attempt at fixing your issue.

**Comment by UserR00T** [comment]
Thanks @Kagemd :D

**Comment by BrokeProtocol** [comment]
Not a Broke Protocol bug or suggestion.
