### ISSUE TITLE
Ball went ouside prison

### ISSUE THREAD

**Issue by UserR00T** [DeathByKorea/BrokeProtocol#234]
I have no idea how, but the ball was outside prison when i came online

https://i.imgur.com/Xpq0ivC.png
https://i.imgur.com/DWNz0d9.png
https://i.imgur.com/SUQyCPK.png

**Comment by Kagemd** [comment]
It's because when somebody blew open the Prison somebody went inside there and took it out. I did that once just to test. It's a bit tricky and I wont say how I achieved it but it can be done.

**Comment by UserR00T** [comment]
Yep, dumb. Forgot that.
