### ISSUE TITLE
Taser Malfunction

### ISSUE THREAD

**Issue by TheReaperG** [DeathByKorea/BrokeProtocol#236]
Everytime the taser hits the person aimed at, it doesn't register sometimes and the person would not be affected. Can someone please fix this issue?

**Comment by Kagemd** [comment]
I have noticed this with other weapons as well. Had a Gamer complaining his weapon wasn't doing damage so I told him to trash it and get another. Same thing with the new weapon so I asked him to disconnect and reconnect. This seemed to resolve the issue but said Gamer stated on his return to the server that he had lost all his ammo.

So hope the little bit more information helps.

**Comment by Johnyknowhow** [comment]
Have also experienced a similar issue with the taser and various guns. Taser doesn't always register a hit, resulting in an un-stunned angry NPC, and sometimes weapons won't deal damage to people who are standing up. Also, sometimes you'll shoot someone, they'll take damage until they get KOed, but won't take any more damage after they're lying on the ground, so you have to finish them off with another gun, or sometimes even a melee weapon.

**Comment by Kagemd** [comment]
When they are Knocked out, aim for the midsection of the Character and it works every time, in my case it seems to work like that.

**Comment by Vixonary** [comment]
If Root is going to respond to this, just note I'm TheReaperG.

**Comment by BrokeProtocol** [comment]
High latency problem, not really a bug.
