### ISSUE TITLE
Mayor system

### ISSUE THREAD

**Issue by Kagemd** [DeathByKorea/BrokeProtocol#240]
To give players a better "Role Play" experience I suggest that you make it so a player can go in to the Police office and interact with a Police (NPC) and file a report against another player. Then the system checks to see if said reported player has any crimes. If they do then an APB (All Points Bulletin) is sent out to all cops issuing an Arrest Warrant which will make the criminals location on the Map (Kind of like the Fire Fighters get).

Prime example would be:

Player 1 kills Player 2
Player 2 enters the Police office, interacts with a designed Police Officer, selects an option for a Warrant from a list of real life Gamer's.
 - The game system will check to see if Player 1 has any crimes and if so, Issue an APB to all Police which are then marked on the Map.

OR 

Instead of interacting with a Police Officer, Player 2 enters the Police Office where he opens the player list and clicks on Player 1 then select File for an Arrest Warrant. However, this option should only be accessible if they are inside the Police Office and no other location. Once an Arrest Warrant has been issued, instead of a "dot" on the map, the map could have a flashing light indicating the turf they are in so it forces them to look for said gamer.

**Comment by UserR00T** [comment]
Great idea, as always.

**Comment by DeathByKorea** [comment]
Mayors added in .70
