### ISSUE TITLE
Heli missles

### ISSUE THREAD

**Issue by SergeyMeyer** [DeathByKorea/BrokeProtocol#241]
I've said this before but this is a slightly different idea. 
I think it would be cool if the missle launchers on helis actually worked. This could be done via a hotkey (such as F or something) with would switch your firemode from weapons in your hand to the hell weapons.

**Comment by UserR00T** [comment]
Nong told us that this will be added next update.

'hi i finished the mayor code, adding flyable planes and rockets to apache now'
