### ISSUE TITLE
Executing actions on yourself while in heli (uncuff, remove from heli etc)

### ISSUE THREAD

**Issue by UserR00T** [DeathByKorea/BrokeProtocol#247]
If you position your head just right you can interact with yourself.
Didn't work in cars, atleast, for me.
You can't do this in a heli if you are a pilot because you can't fly while cuffed.

Screenshot: [https://i.imgur.com/kvSXXRk.png](https://i.imgur.com/kvSXXRk.png)

Video: [https://puu.sh/y8GOH/936622f355.mp4](https://puu.sh/y8GOH/936622f355.mp4)

**Comment by UserR00T** [comment]
Confirmed to be working on newest version, including in cars.

**Comment by BrokeProtocol** [comment]
Cannot reproduce in 0.72, have you tried with unmodified client/server?

**Comment by UserR00T** [comment]
Didn't test it yet on the newest version but it has nothing to do with plugins
