### ISSUE TITLE
Adding teams or groups into the game.

### ISSUE THREAD

**Issue by Cdoggle** [DeathByKorea/BrokeProtocol#249]
If you're on a server and you see someone far in the distance and don't know if that's you're friend or a member of your group, but kill him/her anyway and it was your friend/group member. We've all been in that situation before, and If you haven't, you will someday. My suggestion is adding a little mark above your friends head, signaling you that the person in the distance is your friend. You should also be able to talk to your friend via voice chat no matter where your friend might be. There should also be a 'group chat button' to send a message in chat that can only be viewed by your friend. Same for other group members.

**Comment by BrokeProtocol** [comment]
Duplicate: https://github.com/DeathByKorea/BrokeProtocol/issues/11
