### ISSUE TITLE
Create your own team/gang

### ISSUE THREAD

**Issue by TheCombineSquad03** [DeathByKorea/BrokeProtocol#255]
This Suggestion Is Because Many People Is Helping Each Other Fight Crimes, Rob People, And Many More Co-op Things. So I Just Think About What About Team Making And Recruitment? Also Ive Helped Players Fighting And Robbing Shops, So The Features Is:

=In Creating A Team, You Will Pick What Team Is It Like Traders, Raiders, Or Any More Things That Personalizes Your Team

=You May Edit Your Team's Name, Classes, Description, And Rules

=You May Also Command Your Team Like RTS, Your Team Members Indicates An Icon At Your Map, Also The Map Can Be Also Used To Command Your Members

=Each Team's Members Capacity Is 16

**Comment by BrokeProtocol** [comment]
Merging with similar suggestion: https://github.com/DeathByKorea/BrokeProtocol/issues/249
