### ISSUE TITLE
Adding licenses for licenses does not remove!

### ISSUE THREAD

**Issue by PatrykYopkowskytheyopekutox** [DeathByKorea/BrokeProtocol#262]
Removing licenses are annoying: /

**Comment by UserR00T** [comment]
Have you read the title yourself? Its confusing as hell.

**Comment by UserR00T** [comment]
I will just add beta until I understand where this is about.

**Comment by PatrykYopkowskytheyopekutox** [comment]
I mean that! Licenses should be removed! Or you should add a license for $ 1000 that prevents you from deleting the

**Comment by BrokeProtocol** [comment]
Not constructive.
