### ISSUE TITLE
Cannot start Battle Royale Vote

### ISSUE THREAD

**Issue by Rafe123PL** [DeathByKorea/BrokeProtocol#264]
There is no way to start Battle royale

**Comment by UserR00T** [comment]
Can confirm.

**Comment by NongBenz** [comment]
Can confirm this still occurs 60 seconds after voting, and a battle royale session isnt in progress already?

Vote limiting is in place that stops a player from starting a mission/player vote until 60 seconds passed.

**Comment by NongBenz** [comment]
Ok this has been fixed for release. Thanks!

**Comment by DeathByKorea** [comment]
Fixed, closed.

@NongBenz I'll add you as a contributor so you can close issues
