### ISSUE TITLE
Taking damage while on Boats

### ISSUE THREAD

**Issue by Kasup2** [DeathByKorea/BrokeProtocol#265]
I was on one of the non driveable boats the ones that are just still in the ocean and suddenly i started taking damage. I was on the boat didn't touch the water in anyway.

**Comment by Vixonary** [comment]
Which boat to be exact?

**Comment by Vixonary** [comment]
I have checked and I don't seem to take damage while on the boats.

**Comment by BrokeProtocol** [comment]
Fixed.
