### ISSUE TITLE
Apartments - Buy Furniture still shows outside if you reconnect while inside apartment

### ISSUE THREAD

**Issue by Cdoggle** [DeathByKorea/BrokeProtocol#271]
If you disconnect from a server while you are in your own apartment and reconnect, it puts you outside your apartment and one of the mouse-click options is "Place Furniture" like you're in your apartment. Reconnecting outside your apt. or entering and exiting your apt. fixes the bug.
![image](https://user-images.githubusercontent.com/30122792/33529295-14bc7da8-d83d-11e7-8601-aac97f23a67f.png)

**Comment by NongBenz** [comment]
Maybe this was from a bugged out server in an early beta. I wasn't able to reporoduce.

Please give steps if you're able to do it.

**Comment by BrokeProtocol** [comment]
Fixed, could not reproduce in 0.72
