### ISSUE TITLE
 Bombs

### ISSUE THREAD

**Issue by MereGamer** [DeathByKorea/BrokeProtocol#279]
When you take the bombs that do not count as if you had stolen them.

**Comment by UserR00T** [comment]
In the test version, and, can anyone confirm?

**Comment by MereGamer** [comment]
![20171206212036_1](https://user-images.githubusercontent.com/33642103/33699644-097545e8-dada-11e7-8eb0-66337a20c1f6.jpg)

**Comment by BrokeProtocol** [comment]
Closing this since it was not clear originally if it was a bug or suggestion.

**Comment by MereGamer** [comment]
Is both, since the bombs are hidden, as it can be a crime if nobody sees you
