### ISSUE TITLE
Linux server has memory leak over time

### ISSUE THREAD

**Issue by DeathByKorea** [DeathByKorea/BrokeProtocol#29]
it looks like memory leak or like server is only removing rendered items from ground, or something like this. It's not clearing stuff properly
memory use raised from 800 mb to 2 damn gigabytes with same amount of people in around...lemme se how long server is running
i have constantly 100 people on server, now i have 130 and i have biggest server in BP actually. Server is online for around 2,7 hours now(edited)
and it already raised from "around" 800 mb memory usage to 2 gigabytes, so server is doing something wrong.(edited)
Its raising 720 MB PER HOUR

**Comment by DeathByKorea** [comment]
@Aku - The Chechen Mujahideen Hosting on windows 10 currently I have not seen the same issues or anything really since @NongBenz fixed the last leak. There might be more minor leaks related to dependencies and other libraries that the game uses. something that is different about my particular host env.

**Comment by DeathByKorea** [comment]
its already 3 gigabytes. @Benjipoo yeah propably, we're hosting on Linux so its propably Linux-only issue

**Comment by DeathByKorea** [comment]
more info: Server is working but its not visible on server browser, i dont know what happened to players buuut its using same amount of resources still. Logs are 800+ mbs and contains 48 000000+ lines after something about 3 hours of working :D
and this is what happened with UDP packets during this

![](https://cdn.discordapp.com/attachments/312830115677470721/329306194902646784/udppackets.png)

**Comment by BrokeProtocol** [comment]
Should be fixed with new patch.
