### ISSUE TITLE
Grenade not counted as Contraband

### ISSUE THREAD

**Issue by TheReaperG** [DeathByKorea/BrokeProtocol#294]
The title says it. I think the grenade is supposed to be meant as a contraband, smoke and flashbangs should stay as they are.

![screenshot_15](https://user-images.githubusercontent.com/30944091/33695926-cfd4dedc-db3a-11e7-8e05-5e36d63822b9.png)

**Comment by UserR00T** [comment]
Will get fixed in newest version, 0.73.
