### ISSUE TITLE
Invisible OP bug

### ISSUE THREAD

**Issue by LightVelox** [DeathByKorea/BrokeProtocol#301]
If you get disconected after being knock out and you get back to the game you become invisible, actually your body stays at the floor but you can "move" as a "ghost" and steal everything without anybody noticing,also,unlimitef inventory

**Comment by UserR00T** [comment]
Please let me know if anyone can confirm this.

**Comment by Kagemd** [comment]
I couldn't reproduce this exact bug but I did discover that if you get knocked out, disconnect, reconnect you can move your limp body in a circular motion.

**Comment by DrowningFish6** [comment]
It was fun abusing it

**Comment by BrokeProtocol** [comment]
Unable to reproduce.
