### ISSUE TITLE
Game unresponsive after unrestraining someone that has payed a fine.

### ISSUE THREAD

**Issue by Caza397** [DeathByKorea/BrokeProtocol#303]
I have only been able to reproduce this bug with NPCs. It is reproducible 100% of the time.
Reproducible: Yes
Steps to reproduce: As a Police officer, restrain, search and confiscate illegal items, Fine the NPC and free them. After they have paid the fine all NPC's will stop moving and menu functions will not work. The player is still able to move around but no interaction is possible.

The bug does not occur if the player has not been fined. ie, if there's no contraband. Nor does it occur if you send the NPC to jail.

EDIT: As I was doing further testing, I noticed its the action of fining them that's the trigger for the unresponsiveness and not the unrestraining action.

**Comment by Error3000** [comment]
I also noticed it, I though it was serwer issue but it happens every time.

**Comment by BrokeProtocol** [comment]
Seems to be fixed in 0.72
