### ISSUE TITLE
Aiming weapons at npcs gives crime

### ISSUE THREAD

**Issue by Error3000** [DeathByKorea/BrokeProtocol#314]
Basically I mean that when you are searching npc sometimes they can draw weapon at you cuz they want to kill you but it does not count as crime until they hit you and its not good because , pay ticket system is broken right now (it does not work) so you have to get them to jail in order to truly roleplay and you get more money for taking people with contrabanda and who attacked officer,but sometimes they can kill you.
**The point is to make drawing weapon at cop (in case of npc) a crime.** sorry for bad english and for making the whole thing a mess.

**Comment by LightVelox** [comment]
if they have any crime all you can do now is kill them as a police(dont worry, killing anyone with any crime is not a problem), we'l need to kill all criminals until the next update comes(the ticket problem is already fixed)

**Comment by Error3000** [comment]
The ticket problem is not fixed....

**Comment by LightVelox** [comment]
Its fixed but for the nexr update

**Comment by Error3000** [comment]
The tittle is not exactly right but ok...
