### ISSUE TITLE
Speed test

### ISSUE THREAD

**Issue by Vixonary** [DeathByKorea/BrokeProtocol#320]
I wanna see how fast you can add a label when this is completely random

**Comment by DeathByKorea** [comment]
Wow.
Uhh.

**Comment by DeathByKorea** [comment]
Yeah.

**Comment by Vixonary** [comment]
Rip

**Comment by UserR00T** [comment]
Lets just..

**Comment by Vixonary** [comment]
I guess i'll be doing it sometimes to test reflex

Delete it when we're done though
