### ISSUE TITLE
Buying the high end apartment crashes your game.

### ISSUE THREAD

**Issue by FreeSpy443** [DeathByKorea/BrokeProtocol#331]
I tried buying the new apartment in the 0.71v Test version twice, crashing my game.
[error.log](https://github.com/DeathByKorea/BrokeProtocol/files/1591334/error.log)

**Comment by FreeSpy443** [comment]
Andf if you try restarting on the same character, you'll crash.

**Comment by korterkaks** [comment]
true!

**Comment by korterkaks** [comment]
Actuallly buying any apartment crashes your game :( . I'm a hobo.

**Comment by AGsky21** [comment]
true, I have that problem too

**Comment by BrokeProtocol** [comment]
Fixed with latest update.
