### ISSUE TITLE
I was just walking and it crashed :(

### ISSUE THREAD

**Issue by korterkaks** [DeathByKorea/BrokeProtocol#332]
BrokeProtocol [version: Unity 2017.3.0p1 (4596dd67072f)]

UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0023:0fe96fcd.

Error occurred at 2017-12-28_161644.
C:\Users\Martin\Desktop\Broke Protocol test region1\BrokeProtocol.exe, run by Martin.
25% memory in use.
2048 MB physical memory [2048 MB free].
0 MB paging file [0 MB free].
2048 MB user address space [370 MB free].
Write to location 00000008 caused an access violation.

Context:
EDI:    0x00000060  ESI: 0x007ef2d8  EAX:   0x00000000
EBX:    0x00000008  ECX: 0x00000000  EDX:   0x00000002
EIP:    0x0fe96fcd  EBP: 0x007ef2a8  SegCs: 0x00000023
EFlags: 0x00010202  ESP: 0x007ef290  SegSs: 0x0000002b

Bytes at CS:EIP:
89 3b 83 c6 10 8b 5d f4 89 55 fc 3b 53 04 75 ba 

Stack:
0x007ef290: 1c6203b0 63e3cd00 00342dfe 007ef2b8 ..b....c.-4...~.
0x007ef2a0: 00000000 00000001 007ef6c8 100784f9 ..........~.....
0x007ef2b0: 00000026 1c6203b0 13913fa0 0000000c &.....b..?......
0x007ef2c0: 00000010 007ef6c4 ffffffff 00000000 ......~.........
0x007ef2d0: 00000000 00000008 00000000 00000060 ............`...
0x007ef2e0: 00000000 0000000c 00000000 09c8a000 ................
0x007ef2f0: 00000000 00000010 00000000 0a9957f8 .............W..
0x007ef300: 00000000 00000014 00000000 0b6a0ff0 ..............j.
0x007ef310: 00000000 00000018 00000000 0c3ac7e8 ..............:.
0x007ef320: 00000000 0000004c 00000000 0d0b7fe0 ....L...........
0x007ef330: 00000000 00000040 00000000 0ddc37d8 ....@........7..
0x007ef340: 00000000 00000044 00000000 0f7da7c8 ....D.........}.
0x007ef350: 00000000 00000048 00000000 111f17b8 ....H...........
0x007ef360: 00000000 00000050 00000000 11efcfb0 ....P...........
0x007ef370: 00000000 00000054 00000000 12c087a8 ....T...........
0x007ef380: 00000000 00000000 00000000 00000000 ................
0x007ef390: 00000000 00000000 00000000 00000000 ................
0x007ef3a0: 00000000 00000000 00000000 00000000 ................
0x007ef3b0: 00000000 00000000 00000000 00000000 ................
0x007ef3c0: 00000000 00000000 00000000 00000000 ................
0x007ef3d0: 00000000 00000000 00000000 00000000 ................
0x007ef3e0: 00000000 00000000 00000000 00000000 ................
0x007ef3f0: 00000000 00000000 00000000 00000000 ................
0x007ef400: 00000000 00000000 00000000 00000000 ................
0x007ef410: 00000000 00000000 00000000 00000000 ................
0x007ef420: 00000000 00000000 00000000 00000000 ................
0x007ef430: 00000000 00000000 00000000 00000000 ................
0x007ef440: 00000000 00000000 00000000 00000000 ................
0x007ef450: 00000000 00000000 00000000 00000000 ................
0x007ef460: 00000000 00000000 00000000 00000000 ................
0x007ef470: 00000000 00000000 00000000 00000000 ................
0x007ef480: 00000000 00000000 00000000 00000000 ................
0x007ef490: 00000000 00000000 00000000 00000000 ................
0x007ef4a0: 00000000 00000000 00000000 00000008 ................
0x007ef4b0: 00000010 63e3cd98 00000010 007ef4d4 .......c......~.
0x007ef4c0: 0fe73c22 63a5d030 00000011 63a5d030 "<..0..c....0..c
0x007ef4d0: 63e3cd98 007ef4f4 0fe74214 63a5d030 ...c..~..B..0..c
0x007ef4e0: 63e3cd98 00000010 00000010 00000008 ...c............
0x007ef4f0: 10c17db0 007ef544 0fe96a22 007ef544 .}..D.~."j..D.~.
0x007ef500: 0fe96c95 63e3cda0 10c17e70 10c17db0 .l.....cp~...}..
0x007ef510: 00000010 10c17e70 049fff60 00000010 ....p~..`.......
0x007ef520: 00000000 0001b778 049fff60 0001b778 ....x...`...x...
0x007ef530: 007ef548 0fe96d10 00000000 00000010 H.~..m..........
0x007ef540: 63e3cda0 007ef560 0fe968e6 00000008 ...c`.~..h......
0x007ef550: 00000010 10c16900 00000010 00000008 .....i..........
0x007ef560: 007ef598 0fe981bf 00000008 00000010 ..~.............
0x007ef570: 63e3cc5c 63e3cc5c 00000000 00000074 \..c\..c....t...
0x007ef580: 00000010 10c16900 00000010 00000074 .....i......t...
0x007ef590: 007ef5c8 0fe981bf 00000000 00000006 ..~.............
0x007ef5a0: 007ef5b0 0fe99cf0 00000000 00000006 ..~.............
0x007ef5b0: 007ef604 1007e10a 00000000 00000006 ..~.............
0x007ef5c0: 00000004 00000001 007ef5e8 00000008 ..........~.....
0x007ef5d0: 1007e039 63e3cdd0 63e3cd00 00000000 9......c...c....
0x007ef5e0: 1c6203b0 63e3cd00 63e3cd00 10c1bcf8 ..b....c...c....
0x007ef5f0: 007ef604 0ff7c431 10bd6040 00000000 ..~.1...@`......
0x007ef600: 10c1bcf8 007ef620 0fec401b 63e3cc40 .... .~..@..@..c
0x007ef610: 63e3cc40 00000008 63e3cd00 10c1c004 @..c.......c....
0x007ef620: 007ef62c 1004700a 63e3cc40 007ef64c ,.~..p..@..cL.~.
0x007ef630: 10076aaf 05332060 63e3cd00 63e3cd00 .j..` 3....c...c
0x007ef640: 007ef6e0 0ff38416 63e3cd00 007ef6e8 ..~........c..~.
0x007ef650: 0ff38416 007ef660 63e3cdd0 00000000 ....`.~....c....
0x007ef660: 3f800000 00000000 00000000 00000000 ...?............
0x007ef670: 00000000 3f800000 00000000 00000000 .......?........
0x007ef680: 00000000 00000000 3f800000 00000000 ...........?....
0x007ef690: 3f800000 3f800000 3f800000 3f800000 ...?...?...?...?
0x007ef6a0: 00000000 00000000 00000000 00000000 ................
0x007ef6b0: 3f800000 00000000 00000000 00000000 ...?............
0x007ef6c0: 00000000 00000000 007ef6f0 1007ba5d ..........~.]...
0x007ef6d0: 00342dfe 00000026 1c6203b0 63e3cd00 .-4.&.....b....c
0x007ef6e0: 007ef7f4 1007c343 007ef7f4 44f63040 ..~.C.....~.@0.D
0x007ef6f0: 007ef704 1007870d 00342dfe 007ef7a0 ..~......-4...~.
0x007ef700: 63e3cdd0 007ef7e0 1007c3db 00000001 ...c..~.........
0x007ef710: 23e362d0 1c6203b0 00000003 01a340cc .b.#..b......@..
0x007ef720: 3f800000 00000000 00000000 00000000 ...?............
0x007ef730: 00000000 3f800000 00000000 00000000 .......?........
0x007ef740: 00000000 00000000 3f800000 00000000 ...........?....
0x007ef750: 3f800000 00000000 00000000 00000000 ...?............
0x007ef760: 00000000 3f800000 00000000 00000000 .......?........
0x007ef770: 00000000 00000000 3f800000 00000000 ...........?....
0x007ef780: 00000000 00000000 00000000 00000000 ................
0x007ef790: 007ef800 007ef7b0 100f8f01 507f5140 ..~...~.....@Q.P
0x007ef7a0: 00000000 00000000 00000000 3f800000 ...............?
0x007ef7b0: 007ef7e0 100f5c70 007ef800 00000000 ..~.p\....~.....
0x007ef7c0: 63e3cd00 100f74e0 00000000 00000000 ...c.t..........
0x007ef7d0: 10140ad9 007ef810 507f5150 00000000 ......~.PQ.P....
0x007ef7e0: 007ef808 10157404 007ef800 63e3cc40 ..~..t....~.@..c
0x007ef7f0: 00b87668 00b87668 10157404 1c6203b0 hv..hv...t....b.
0x007ef800: 00000001 194aec00 007ef858 192f4d04 ......J.X.~..M/.
0x007ef810: 507f5140 23e383f0 00000001 00000000 @Q.P...#........
0x007ef820: 007ef860 00b6b860 007ef878 03221011 `.~.`...x.~...".
0x007ef830: 1495e5c8 00b6b860 23e362d0 194aec00 ....`....b.#..J.
0x007ef840: 007ef848 507f5150 23e362d0 194aec00 H.~.PQ.P.b.#..J.
0x007ef850: 007ef858 192f4cbb 007ef878 192f4c98 X.~..L/.x.~..L/.
0x007ef860: 507f5140 23e383f0 00000001 507f5140 @Q.P...#....@Q.P
0x007ef870: 00000000 1c0cdad8 007ef8d8 084e3c38 ..........~.8<N.
0x007ef880: 507f5140 23e383f0 00000045 032210f1 @Q.P...#E.....".
0x007ef890: 18e66040 23e362d0 131069a0 007efa20 @`...b.#.i.. .~.
0x007ef8a0: 007ef8e0 007ef928 00000000 18e7a6a0 ..~.(.~.........
0x007ef8b0: 00b6b861 00b87668 507f5150 507f5140 a...hv..PQ.P@Q.P
0x007ef8c0: 007efa0e 00000000 507f5140 00000000 ..~.....@Q.P....
0x007ef8d0: 18e7a6a0 007efa20 007ef928 192f36eb .... .~.(.~..6/.
0x007ef8e0: 194aec00 23e362d0 194aec38 1c7b9000 ..J..b.#8.J...{.
0x007ef8f0: 00002000 194aec3c 194aec40 19318d00 . ..<.J.@.J...1.
0x007ef900: 1c44dab0 22935b70 007ef958 194aec3c ..D.p[."X.~.<.J.
0x007ef910: 1c7b9000 23e362d0 194aec00 18e66040 ..{..b.#..J.@`..
0x007ef920: 007efb14 12f75290 007ef958 17392d9d ..~..R..X.~..-9.
0x007ef930: 18e7a6a0 00b6b860 00000000 18249a0c ....`.........$.
0x007ef940: 240b5a10 007efa64 007ef994 1739312b .Z.$d.~...~.+19.
0x007ef950: 23eb6bc0 007efba3 007ef998 17392e61 .k.#..~...~.a.9.
0x007ef960: 18e7a6a0 007efba3 007ef9a0 007ef9a0 ......~...~...~.
0x007ef970: 007ef9a0 06680e49 00000000 00000000 ..~.I.h.........
0x007ef980: 007efa20 007efa20 00000000 00000000  .~. .~.........
0x007ef990: 007efbb8 007efa20 007ef9d4 064f3d35 ..~. .~...~.5=O.
0x007ef9a0: 00000000 007efb14 007efbb8 17392d70 ......~...~.p-9.
0x007ef9b0: 007efa20 12f75290 05a10fb0 00b51e98  .~..R..........
0x007ef9c0: 00000000 00000000 00000000 00000000 ................
0x007ef9d0: 031e2e60 007ef9fc 0667af50 12f75290 `.....~.P.g..R..
0x007ef9e0: 00000000 007efb14 1bda5790 007efa20 ......~..W.. .~.
0x007ef9f0: 12f75290 007efbb8 05a10fb0 007efa54 .R....~.....T.~.
0x007efa00: 066816f6 12f75290 00000000 007efb14 ..h..R........~.
0x007efa10: 007efbb8 007efa20 12f75290 00000000 ..~. .~..R......
0x007efa20: 00000000 205e9aa0 007efa50 007efa50 ......^ P.~.P.~.
0x007efa30: 04b55d74 24a0d080 04b55d00 007efa88 t].....$.]....~.
0x007efa40: 0ff38598 007efaa8 238147c0 23810100 ......~..G.#...#
0x007efa50: 12f9f621 007efa74 100fd04f 12f75290 !...t.~.O....R..
0x007efa60: 00000000 007efb14 007efbb8 007efbb8 ......~...~...~.
0x007efa70: 007efab4 007efa9c 100f88a9 007efaa8 ..~...~.......~.
0x007efa80: 12f75290 00000000 007efab4 007efbb8 .R........~...~.
0x007efa90: 00000000 04b55d74 007efbb8 007efba4 ....t]....~...~.
0x007efaa0: 100e6378 007efbac 007efbb8 00000000 xc....~...~.....
0x007efab0: 1fdafe10 007efafc 007efae0 007efba3 ......~...~...~.
0x007efac0: 007efaec 12fc89e8 22529300 007efafc ..~.......R"..~.
0x007efad0: 007efbf0 00000000 229301e0 12fc89e8 ..~........"....
0x007efae0: 007efbe8 100e48a6 007efbe4 00000000 ..~..H....~.....
0x007efaf0: 00000000 1d883e80 229301e0 00000001 .....>....."....
0x007efb00: 00000000 00000000 0527d400 00000000 ..........'.....
0x007efb10: 00000000 18e7a6a0 007efabc 00000000 ..........~.....
0x007efb20: 00000000 00000000 00000000 00000000 ................
0x007efb30: 00000000 00000000 00000000 00000000 ................
0x007efb40: 00000000 00000005 0000000a 00000002 ................
0x007efb50: 04d70520 00000002 4de809e2 00000000  ..........M....
0x007efb60: 00000000 00000000 00000000 00000000 ................
0x007efb70: 00000000 00000002 1bd34d30 12f75290 ........0M...R..
0x007efb80: 00000000 00000000 0001c43a 131475c8 ........:....u..
0x007efb90: 1c0c92a0 007e0101 00000000 18e7a6a0 ......~.........
0x007efba0: 00000000 007efbbc 100e6d6b 007efbb8 ......~.km....~.
0x007efbb0: 1fdafe10 05a10fb0 00000000 007efbc8 ..............~.
0x007efbc0: 100e4e68 00000000 007efc20 0ff3a5f4 hN...... .~.....
0x007efbd0: 1c6e7ef0 1fdafe10 74589500 7458fc60 .~n.......Xt`.Xt
0x007efbe0: 7459eec0 12f9f621 40433479 100e49f2 ..Yt!...y4C@.I..
0x007efbf0: 00000000 04d4a9f0 22529300 007efc28 ..........R"(.~.
0x007efc00: 100e7bf7 205ef7e0 100e4b80 100e4e30 .{....^ .K..0N..
0x007efc10: 1c6e7ef0 1fdafe10 000008f5 04b55d50 .~n.........P]..
0x007efc20: 007efc64 1002078e 00000002 10021bf7 d.~.............
0x007efc30: 104a09d1 1049fe98 00000001 00000001 ..J...I.........
0x007efc40: 00000000 00020bf6 00000200 00000004 ................
0x007efc50: 021b03bf 0ead63d8 000003bf 0000021b .....c..........
0x007efc60: 00000840 007efe00 104a1c62 00000000 @.....~.b.J.....
0x007efc70: 00fb32e8 00929000 04b2bad0 0000004d .2..........M...
0x007efc80: 00740020 00730065 00200074 0000004d  .t.e.s.t. .M...
0x007efc90: 00000044 04b33d90 0000005c 00720042 D....=..\...B.r.
0x007efca0: 006b006f 00500065 0000005b 00000044 o.k.e.P.[...D...
0x007efcb0: 04b2bb20 0000004e 00780065 00000065  ...N...e.x.e...
0x007efcc0: 00000000 0000004e 00000044 04b464d0 ....N...D....d..
0x007efcd0: 00000012 00000006 00000808 00b20000 ................
0x007efce0: 0000000f 00000044 00000000 6b6f7242 ....D.......Brok
0x007efcf0: 6f725065 6f636f74 0000006c 0000000d eProtocol.......
0x007efd00: 00000044 00000028 00b2765c 00000000 D...(...\v......
0x007efd10: 007efdc0 000003ec 01005ca8 00000000 ..~......\......
0x007efd20: 04b3fa90 00000077 00b46a78 0000000a ....w...xj......
0x007efd30: 00000000 00000077 00000044 04b33cd0 ....w...D....<..
0x007efd40: 00000057 000003ec 000100c0 fffffffe W...............
0x007efd50: 00000057 00000044 04b33d90 00000052 W...D....=..R...
0x007efd60: 00000000 000002eb 00af0000 00000052 ............R...
0x007efd70: 00000044 04b2bb70 00000046 0000026b D...p...F...k...
0x007efd80: 0000036c 01000008 00000046 00000044 l.......F...D...
0x007efd90: 00000000 65646968 646e6957 7700776f ....hideWindow.w
0x007efda0: 00000002 0000000a 00000044 04b46490 ........D....d..
0x007efdb0: 04b464ac 04b464ac 00000438 00000780 .d...d..8.......
0x007efdc0: 00000001 00000000 6374652f 00646500 ......../etc.ed.
0x007efdd0: 00676966 00000800 00000004 00000044 fig.........D...
0x007efde0: 00000000 65726170 5748746e 0000444e ....parentHWND..
0x007efdf0: 00fa1988 0000000a 00000044 007efe00 ........D.....~.
0x007efe00: 007efe1c 104a1da5 00fa0000 00000000 ..~...J.........
0x007efe10: 00b22058 00000001 00fb32e8 007efe34 X .......2..4.~.
0x007efe20: 00fa1275 00fa0000 00000000 00b22058 u...........X ..
0x007efe30: 00000001 007efe80 00fa1437 00fa0000 ......~.7.......
0x007efe40: 00000000 00b22058 00000001 cfe1069b ....X ..........
0x007efe50: 00fa14b0 00fa14b0 00929000 00000000 ................
0x007efe60: c0000005 00fa14b0 007efe4c 007eecc0 ........L.~...~.
0x007efe70: 007efecc 00fa1fb0 cf64f783 00000000 ..~.......d.....
0x007efe80: 007efe94 77448654 00929000 77448630 ..~.T.Dw....0.Dw
0x007efe90: 925d8e3f 007efedc 77944a47 00929000 ?.]...~.GJ.w....
0x007efea0: 6ddb512c 00000000 00000000 00929000 ,Q.m............
0x007efeb0: c0000005 00000000 007eeca0 74a9d5d0 ..........~....t
0x007efec0: 6ddb512c 007efea0 007eeca0 007efee4 ,Q.m..~...~...~.
0x007efed0: 77956a20 1a385500 00000000 007efeec  j.w.U8.......~.
0x007efee0: 77944a17 ffffffff 77969ed1 00000000 .J.w.......w....
0x007efef0: 00000000 00fa14b0 00929000 00000000 ................
0x007eff00: 00000000 00000000 00000000 00000000 ................
0x007eff10: 00000000 00000000 00000000 00000000 ................
0x007eff20: 00000000 00000000 00000000 00000000 ................
0x007eff30: 00000000 00000000 00000000 00000000 ................
0x007eff40: 00000000 00000000 00000000 00000000 ................
0x007eff50: 00000000 00000000 00000000 00000000 ................
0x007eff60: 00000000 00000000 00000000 00000000 ................
0x007eff70: 00000000 00000000 00000000 00000000 ................
0x007eff80: 00000000 00000000 00000000 00000000 ................
0x007eff90: 00000000 00000000 00000000 00000000 ................
0x007effa0: 00000000 00000000 00000000 00000000 ................
0x007effb0: 00000000 00000000 00000000 00000000 ................
0x007effc0: 00000000 00000000 00000000 00000000 ................
0x007effd0: 00000000 00000000 00000000 00000000 ................
0x007effe0: 00000000 00000000 00000000 00000000 ................
0x007efff0: 00000000 00000000 00000000 00000000 ................

Can't show you that modul stuff. Dunno what it's for but it has info about my pc on it.

== [end of error.log] ==

**Comment by UserR00T** [comment]
Next time post the error.log as file.

It has been reported though discord already, thanks for your time though.
