### ISSUE TITLE
Bug , Police (Doing ticket)

### ISSUE THREAD

**Issue by HamsterOh** [DeathByKorea/BrokeProtocol#337]
# **Bug**

_Hi, i've found a bug to fix fastly.

Sometimes, i'm playing on my local server for developping things or for fun.
The 29/12/2017, i've played on my local server as Police man! It were funny, but...
I've found some illegal stuff on a NPC. I take them, then i wrote a ticket for his crimes: Illegal stuff.
When i wrote a ticket for that, nothing happened. The server just freeze, i were able to do nothing (Can't handcuff people, search in their backpack...)

It might be my game, it might be broken? I don't think. 

- When this bug happen ?: **When you write a ticket for something. (Only when the NPC pay the ticket i think).**

- What version ?: **On the 0.70 of Broke PROTOCOL**

**Comment by Error3000** [comment]
It was reported before. But yea It needs to be fixed fast because its literaly game-breaking

**Comment by UserR00T** [comment]
Duplication of #303
