### ISSUE TITLE
Crashing/Fines

### ISSUE THREAD

**Issue by Zombieweasel3000** [DeathByKorea/BrokeProtocol#339]
This game keeps crashing over and over for no reason whats so ever. Please fix this and also when you fine a NPC it freezes everything and you can't do anything.

**Comment by BrokeProtocol** [comment]
Still happens in beta version v0.71c.

**Comment by BrokeProtocol** [comment]
Should be fixed in latest update 0.71a

**Comment by Zombieweasel3000** [comment]
Forgot to respond, thanks for replying to me and the issue has been
resolved..
