### ISSUE TITLE
Having problems getting in servers

### ISSUE THREAD

**Issue by GamingFlorisNL** [DeathByKorea/BrokeProtocol#34]
i have some problems getting into servers you know, you're in a camera angle wwhen you have the logiin screen
after i log in and click away the information window, i freeze iun that camra angle. right now i cam only play in offline mode. can you please help me. it happens on every server, and all my accounts i made. i also un-installed and re-installed the game but it just doesn't work

**Comment by BrokeProtocol** [comment]
Should be fixed with new patch.
