### ISSUE TITLE
Summary of What I want for 0.8 (Or the next big update)

### ISSUE THREAD

**Issue by Cybermetic** [DeathByKorea/BrokeProtocol#340]
1.GUI graphical overhaul- Right now all the menus look ugly, especially the inventory. They all need a big graphical revamp. The inventory needs a better equipped side and item name search. May also need sorting different items into different tabs.
2.More places to rob/crime at-Instead of all the robberies being either hands up to someone or shooting someone and grabbing their suitcase. Add more bank like robberies. Maybe like a vault on a yacht in the ocean, or perhaps stealing military equipment from an aircraft carrier, or perhaps a destruction mission on something, the possibilities are endless.
3.More useful furniture-perhaps a working coffee machine, or a safe that store money as a value (Like the ATM) instead of as an item (or maybe just a great place to hide some drugs) Make the refrigerator also store items, put items on wall racks and displays, the possibilities are endless.
4.Add more option toggelability- right now it seams the only options that matter are for servers. Add more options for graphical quality, V-Sync all that stuff. Maybe add an option for servers removing certain items or perhaps toggling PVP.

**Comment by Error3000** [comment]
lol I love the ,,What I want'' thing, sorry it just sound so silly to me xd

**Comment by BrokeProtocol** [comment]
Split your suggestions into their own issue, so they are easier to search and browse.
