### ISSUE TITLE
New Stuff

### ISSUE THREAD

**Issue by AndysComing** [DeathByKorea/BrokeProtocol#341]
I would like there to be credit cards+printed cash, and make it so you could "hack" files and sell them, or hack banks. I would also like there to be more places to rob not just the bank, remove police from every building, but make them spawn randomly, also make the AI a little smarter but make there be more crime for police. Add more jobs like cloth maker, and make a clothes shop. Add a ammo locker to the police station, and add more interior to buildings. Add a pool to make the game look more "realistic" and add more buildings (with interior) Add an architect job, and try to code something so that you can fight going to jail by using a lawyer, the better the lawyer the better the chance of not being arrested.

To be honest, there **is a lot to be added** but take your time, making this game even better 
(:

**Comment by BrokeProtocol** [comment]
Could you split your suggestions into their own issue so it's easier for Nong to view at a glance? There is many suggestions that get posted in a single issue, but it's next to impossible to filter or search when it's like blobbed together. Thanks.
