### ISSUE TITLE
Crashing and wont login in

### ISSUE THREAD

**Issue by Astrofiregames** [DeathByKorea/BrokeProtocol#344]
The game crashes while im playing on a online server and then I try to join back into the same server and wont let me join back in.I try multiple times and it most times doesn't let me join in and sometimes it does.I asked my friend and he has the exact same problem. By the way this happens everyday.

**Comment by UserR00T** [comment]
Is the server running any plugins?

**Comment by BrokeProtocol** [comment]
Closing, crashes should be fixed.

**Comment by Astrofiregames** [comment]
Thanks
