### ISSUE TITLE
The sudden police in the bank

### ISSUE THREAD

**Issue by AGsky21** [DeathByKorea/BrokeProtocol#345]
There is a strange police man in the bank, I don´t know if it is only in the bank bulding.
The problem is when I am in the bank, I knock down the first police man, the second one and the third one, but suddenly appears another police man that wasn´t in the building (It isn't a respawned cop). He spawns, kills me and then disappears, it is too annoying because I cannot do the "Gand Larceny" in this version (I've tried more than 7 times and I have gotten nothing).
Thanks.

**Comment by BrokeProtocol** [comment]
The new update has added this functionality to allow police to enter interiors to chase criminals: "Added AI police entering buildings with wanted criminals."
