### ISSUE TITLE
ням кэт#6654

### ISSUE THREAD

**Issue by NYANCATZXC** [DeathByKorea/BrokeProtocol#348]
bug with version 666 - sits on the table + 2 jump and you on the ceiling

**Comment by BrokeProtocol** [comment]
Game version is 0.71.

**Comment by NYANCATZXC** [comment]
well, the bug was nobody repaired

**Comment by NYANCATZXC** [comment]
and you closed it

**Comment by UserR00T** [comment]
Duplication of #104 .
