### ISSUE TITLE
(Real) Battle Royale Game Mode

### ISSUE THREAD

**Issue by Cdoggle** [DeathByKorea/BrokeProtocol#360]
I know there's already a battle royale game mode from the 'Missions' menu, but I want battle royale like in PUBG, Fortnite BR, King of the Kill... I could list so many battle royale games here. What I mean is players look for weapons that don't despawn. The map is also much bigger and you can see where the border will end up.

**Comment by BrokeProtocol** [comment]
Duplicate: https://github.com/DeathByKorea/BrokeProtocol/issues/284
