### ISSUE TITLE
When disconnecting and reconnecting while knocked out, your character is able to move freely

### ISSUE THREAD

**Issue by Cdoggle** [DeathByKorea/BrokeProtocol#362]

**Comment by BrokeProtocol** [comment]
Can you test to see if it makes you invisible as well?

**Comment by Cdoggle** [comment]
It does make you invisible. When viewing in third-person, the camera focuses on the knocked out body. If the body is in view, you can see the body through walls. The glitch also happens when you are released from jail while knocked out.

**Comment by BrokeProtocol** [comment]
Thanks, check to see if you're invisible for other players too or if it's just for self.

**Comment by Cdoggle** [comment]
Since you're technically knocked out, other players can see your ragdoll body, but likely not where the client sees the player. I'm gonna test it out with a friend later.

**Comment by UserR00T** [comment]
Will get fixed in newest version, 0.73.
