### ISSUE TITLE
Unable to Buy Furniture

### ISSUE THREAD

**Issue by TheReaperG** [DeathByKorea/BrokeProtocol#363]
If you buy the 10k apartment and buy anything from the furniture shop, if you place the item down, the whole furniture shop will come up completely blank and you can't buy any other furniture unless you sell your apartment and buy another one.

EDIT: You can buy furniture but only one and you're required to sell the item in order to buy another one.

![vqb9bpl](https://user-images.githubusercontent.com/30944091/34861342-2aead300-f79f-11e7-8904-0dfdd75c3412.png)

**Comment by Error3000** [comment]
Fix this asap (my personal wish) its annoying because I used to baricade my chests in one room and now I can't

**Comment by UserR00T** [comment]
Will get fixed in newest version, 0.73.
