### ISSUE TITLE
Multiplayer not working

### ISSUE THREAD

**Issue by bugreport123** [DeathByKorea/BrokeProtocol#379]
Just fix it i have 10k sitting in a box soo fix it

**Comment by TheReaperG** [comment]
Did you not see the announcement in discord? The master server is down, so you can’t connect to other servers for the meantime. Just be patient and wait till it’s fixed

**Comment by bugreport123** [comment]
Thx i didnt get the messege

**Comment by TheReaperG** [comment]
No problem, happy to help :D
