### ISSUE TITLE
Stranger Things...

### ISSUE THREAD

**Issue by Pencyl321** [DeathByKorea/BrokeProtocol#396]
Ekhm so i want to join server then i just got lagged and i can't joned. After restart of computer, I want to go to my apartament then i thought i gonna get heart attack. I saw nothing, all my guns, ammos, furnitures gone. I don't know why but it happend. Iost all my stuff worth like 100k. Please guys fix it or tell me what is going on.
Here is SS:
http://steamcommunity.com/sharedfiles/filedetails/?id=1343883757  

http://steamcommunity.com/sharedfiles/filedetails/?id=1343846987  

http://steamcommunity.com/sharedfiles/filedetails/?id=1343847184

**Comment by Error3000** [comment]
You basically lost it, happened to most of us (I guess). It's sad but you can't really do much about it :(
Back to the grind as they say.

**Comment by DeathByKorea** [comment]
Known Bug, Your stuff is gone sorry, please contact the server owner to see if you can get your items back
