### ISSUE TITLE
Army guys problem

### ISSUE THREAD

**Issue by Ghostduplicator7** [DeathByKorea/BrokeProtocol#403]
So while playing I saw one of the Army guys cuffed then I searched him and it was then when I found 10 pistols and 27 MP5SDs with 2700 SMG ammo and I tried cuffing other army guys and seeing if it works and I found out that all army guys have a lot of guns and weaponary with them which makes guns as cheap as burgers...So basically you need to change the spawning options for the army guys to limit down the amount of guns they have.

**Comment by UserR00T** [comment]
Seems to be fixed on version 0.78a.
