### ISSUE TITLE
can't download the game

### ISSUE THREAD

**Issue by tomer112233** [DeathByKorea/BrokeProtocol#421]
i bougt the game short time ago and today i have tryed to download the game and it says "content file is locked"..
![image](https://user-images.githubusercontent.com/39431688/40266832-bc9ab8a0-5b5a-11e8-90f4-3e101c50af2c.png)

**Comment by UserR00T** [comment]
Hey tomer,
Please download [IOBit File Unlocker](https://www.iobit.com/ko/iobit-unlocker.php) and select your game folder by steam library -> Broke Protocol -> Properties -> Local -> Browse local files to unlock the files.

**Comment by UserR00T** [comment]
Closing due to no response in a long time.
