### ISSUE TITLE
Suggestions for the game

### ISSUE THREAD

**Issue by Ghostduplicator7** [DeathByKorea/BrokeProtocol#66]
Here are some good suggestions for this game : 
1. make some kind of sleeping system to make the game more realistic I mean how the heck do u stay for a week without sleeping  
2.Please please please try to make planes or helicopters or jets this makes the game much more fun for people     
3.Try to make some in-game faces to describe ur feelings or anything like that if not please make it while registering an account        
4.Try to add an RPG kind of gun on the top of police department or something like that but u need a key to get up *_on the rooftop_* just like the prison kind of thing where u can with the cops only        
5.Try to make running faster bec compared to the normal movment it's approximately the same      
*_PS: I know that this would take a long amount of time but I a huge fan of this game and I would wait for that to become true and I hope that u see my message, thanks for your attention_*

**Comment by BrokeProtocol** [comment]
Could you please split up your suggestions in separate "issues" so it's easier to view when browsing all issues at once. Just trying to clean up a bit so it's easier for NongBenz to get a overview of what everyone wants. Thanks.
