### ISSUE TITLE
Firefighters destroying cars and extinguishing fires are still payed

### ISSUE THREAD

**Issue by DeathByKorea** [DeathByKorea/BrokeProtocol#83]
Suggestion: track who destroys cars to stop a single firefighter getting payed for a fire they started

**Comment by BrokeProtocol** [comment]
I don't quite understand what you are suggesting, are you saying if a firefighter intentionally blew up a car and then put out the fire, he wouldn't get any money for it? If that is so, then how would a firefighter make money? The main money source for firefighters is to intentionally blow up vehicles, if you removed that, then there would be absolutely no point of going Firefighter.

**Comment by DeathByKorea** [comment]
Closed, Intended behavior?

**Comment by BrokeProtocol** [comment]
Yeah, unless Nong added other methods for making money.
