### ISSUE TITLE
Gun Licences

### ISSUE THREAD

**Issue by TheLastSpectre** [DeathByKorea/BrokeProtocol#87]
We should be able to purchase licenses for guns and knives and whatnot that allows us to carry them, as it is really annoying to be considered carrying contraband when you have a weapon that you simply NEED to defend yourself in this cutthroat game. The licenses should be expensive, but allow us to carry civilian grade firearms (all the pistols and maybe a shotgun). A license for higher grade weapons should also be a thing. This should be added so corrupt cops can't steal all the weapons you worked so hard to buy and then fine YOU for it too.

**Comment by DarkRosanne** [comment]
Maybe not knives and such *I believe myself that melee weapons should be allowed dependant on your job so fireman = axe idea* but I do agree that a pistol license would be a nice idea, to get from the PD and such. I don't think shotgun should be counted as that is one of the High Danger Weapons as it can quite easily bypass any armour protection with 2 close range shots (one which usually just knocks them down) or a full close range head-shot in some cases too.

**Comment by UserR00T** [comment]
Nong told us that he will add this next update.
